version: '3.7'
services:
  proxy:
    image: nginx
    volumes:
    - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 10003:80
    depends_on:
      - static
      - api
      - pushpin
    restart: unless-stopped
    networks:
      - sagenet
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.testrecipesagesecure.entrypoints=websecure"
      - "traefik.http.routers.testrecipesagesecure.rule=Host(`testrecipesage.raygunhosting.com`)"
  static:
    image: julianpoy/recipesage-selfhost:static-latest
    restart: unless-stopped
    networks:
      - sagenet
      - proxy
  api:
    image: julianpoy/recipesage-selfhost:api-latest
    depends_on:
      - postgres
      - elasticsearch
      - pushpin
      - browserless
    command: /app/www
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_REGION=us-west-2
      - AWS_BUCKET=recipesage-selfhost
      - AWS_ENDPOINT=http://minio:9000/ # Needed for minio, remove for s3 - should be the internal container address to minio
      - AWS_S3_PUBLIC_PATH=/minio/recipesage-selfhost/ # Needed for minio, remove for s3 - should be a public facing address/path directed to minio (by default nginx proxy handles)
      - AWS_S3_FORCE_PATH_STYLE=true # Needed for minio, remove for s3
      - AWS_S3_SIGNATURE_VERSION=v4 # Needed for minio, remove for s3
      - NODE_ENV=selfhost
      - VERBOSE=false
      - VERSION=selfhost
      - POSTGRES_DB=recipesage_selfhost
      - POSTGRES_USER=recipesage_selfhost
      - POSTGRES_PASSWORD=recipesage_selfhost
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_SSL=false
      - POSTGRES_LOGGING=false
      - GCM_KEYPAIR
      - SENTRY_DSN
      - GRAYLOG_HOST=localhost
      - GRAYLOG_PORT
      - GRIP_URL=http://pushpin:5561/
      - GRIP_KEY=changeme
      - ELASTIC_ENABLE=true
      - ELASTIC_IDX_PREFIX=rs_selfhost_
      - ELASTIC_CONN=http://elastic:recipesage_selfhost@elasticsearch:9200
      - ELASTIC_PASSWORD=recipesage_selfhost
      - STRIPE_SK
      - STRIPE_WEBHOOK_SECRET
      - BROWSERLESS_HOST=browserless
      - BROWSERLESS_PORT=3000
      - INGREDIENT_INSTRUCTION_CLASSIFIER_URL=http://ingredient-instruction-classifier:3000/
    restart: unless-stopped
    networks:
      - sagenet
      - proxy
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=recipesage_selfhost
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - sagenet
      - proxy
  pushpin:
    image: fanout/pushpin:1.27.0
    environment:
      - target=api:3000
    restart: unless-stopped
    networks:
      - sagenet
      - proxy
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=recipesage_selfhost
      - POSTGRES_USER=recipesage_selfhost
      - POSTGRES_PASSWORD=recipesage_selfhost
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - sagenet
      - proxy
  browserless:
    image: browserless/chrome:1.28.0-chrome-stable
    environment:
      - MAX_CONCURRENT_SESSIONS=3
      - MAX_QUEUE_LENGTH=10
    restart: unless-stopped
    networks:
      - sagenet
      - proxy
  ingredient-instruction-classifier:
    image: julianpoy/ingredient-instruction-classifier:latest
    environment:
      - SENTENCE_EMBEDDING_BATCH_SIZE=200
      - PREDICTION_CONCURRENCY=4
    restart: unless-stopped
    networks:
      - sagenet
      - proxy
  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - miniodata:/data
    command: server /data
    restart: unless-stopped
  create-minio-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: sh -c
    command: >
      "
      /usr/bin/mc config host add myminio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb myminio/recipesage-selfhost;
      /usr/bin/mc policy set public myminio/recipesage-selfhost;
      exit 0;
      "
    networks:
      - sagenet
      - proxy
volumes:
  elasticsearchdata:
    driver: local
  postgresdata:
    driver: local
  miniodata:
    driver: local

networks:
  sagenet:
  proxy:
    external: True
